import type { SavedItem } from "./types";

interface SeedItem {
  sourceUrl: string;
  sourceType: SavedItem["sourceType"];
  creatorName: string;
  title: string;
  userNote: string;
  captionText?: string;
  transcriptText?: string;
  collections: string[];
  tags: string[];
  daysAgo: number;
  lastOpenedDaysAgo?: number;
  openCount: number;
  isFavorite?: boolean;
  isPinned?: boolean;
  needsReview?: boolean;
  availabilityStatus?: SavedItem["availabilityStatus"];
}

export const SEED_ITEMS: SeedItem[] = [
  {
    sourceUrl: "https://www.instagram.com/reel/PYCHATBOT01/",
    sourceType: "instagram_reel",
    creatorName: "codewitharjun",
    title: "Build a Python chatbot in 90 seconds",
    userNote: "Use this for my ML project. Simple retrieval bot, then swap in embeddings.",
    captionText: "Beginner Python chatbot with Flask. Save this for your next hackathon.",
    transcriptText:
      "Today we build a tiny Python chatbot. First install flask, then load a FAQ file.",
    collections: ["Coding", "AI/ML", "Inbox"],
    tags: ["python", "chatbot", "beginner", "project-idea"],
    daysAgo: 210,
    lastOpenedDaysAgo: 40,
    openCount: 3,
    isFavorite: true,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/HYDCAFE22/",
    sourceType: "instagram_reel",
    creatorName: "hydfoodwalks",
    title: "Hyderabad cafes with outdoor seating",
    userNote: "Weekend list with A. Need shade and sockets. Jubilee Hills / Banjara.",
    captionText: "Outdoor seating cafes in Hyderabad that are actually good for work.",
    collections: ["Travel", "Inbox"],
    tags: ["hyderabad", "cafe", "outdoor", "work-from-cafe"],
    daysAgo: 48,
    lastOpenedDaysAgo: 2,
    openCount: 4,
    isFavorite: true,
    isPinned: true,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/TORCHBEGIN/",
    sourceType: "instagram_reel",
    creatorName: "mlstreetnotes",
    title: "Beginner PyTorch in one sitting",
    userNote: "Start here before the course project. Tensors, autograd, one training loop.",
    captionText: "PyTorch tutorial for complete beginners. No PhD required.",
    transcriptText: "A tensor is just a fancy array. Let me show a training loop in 20 lines.",
    collections: ["AI/ML", "College"],
    tags: ["pytorch", "beginner", "tutorial"],
    daysAgo: 22,
    lastOpenedDaysAgo: 6,
    openCount: 2,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/PANEERHIKE/",
    sourceType: "instagram_reel",
    creatorName: "homekitchensaab",
    title: "High-protein palak paneer, 25 minutes",
    userNote: "Healthy paneer recipe. Swap cream for cashew + milk. Meal prep Sunday.",
    captionText: "Palak paneer that does not taste like diet food.",
    collections: ["Recipes"],
    tags: ["paneer", "high-protein", "recipe", "vegetarian"],
    daysAgo: 11,
    lastOpenedDaysAgo: 1,
    openCount: 1,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/HOOKCUT03/",
    sourceType: "instagram_reel",
    creatorName: "editsbykira",
    title: "Five video editing hooks that still work",
    userNote: "Steal the pattern, not the footage. Try hook #2 on the Thursday reel.",
    captionText: "Hooks I used this month. Sound on.",
    transcriptText: "Hook two is a false start. You begin the payoff, then rewind.",
    collections: ["Editing Ideas"],
    tags: ["hook", "editing", "retention"],
    daysAgo: 9,
    openCount: 0,
    needsReview: false,
  },
  {
    sourceUrl: "https://www.instagram.com/p/SQLNOTES88/",
    sourceType: "instagram_carousel",
    creatorName: "data.desk",
    title: "SQL window functions cheat carousel",
    userNote: "Need this for the analytics assignment. ROW_NUMBER vs RANK.",
    captionText: "Save this SQL carousel. Window functions without the headache.",
    collections: ["Coding", "College"],
    tags: ["sql", "study", "cheat-sheet"],
    daysAgo: 70,
    lastOpenedDaysAgo: 18,
    openCount: 5,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/DEADHACK99/",
    sourceType: "instagram_reel",
    creatorName: "hacknightclub",
    title: "48-hour hackathon checklist",
    userNote: "Saved this 3 months ago for a hackathon. Review before next college fest.",
    collections: ["Coding", "College", "Watch Later"],
    tags: ["hackathon", "checklist"],
    daysAgo: 96,
    openCount: 0,
    needsReview: true,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/MISSING01/",
    sourceType: "instagram_reel",
    creatorName: "ghosted.creator",
    title: "Color grade recipe — teal shadows",
    userNote: "Original looks gone. Keep the notes: teal shadows, warm skin, -12 highlights.",
    collections: ["Editing Ideas"],
    tags: ["color", "thumbnail"],
    daysAgo: 130,
    lastOpenedDaysAgo: 80,
    openCount: 1,
    availabilityStatus: "reported_dead",
  },
  {
    sourceUrl: "https://www.instagram.com/reel/SQUATFORM/",
    sourceType: "instagram_reel",
    creatorName: "coach.naina",
    title: "Goblet squat form cues",
    userNote: "Knees track toes. Brace before descent. Film a set tomorrow.",
    collections: ["Fitness"],
    tags: ["workout", "form", "legs"],
    daysAgo: 33,
    openCount: 0,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/OFFERSTACK/",
    sourceType: "instagram_reel",
    creatorName: "operatorhours",
    title: "How to write a boring but clear offer",
    userNote: "Business idea: one sentence offer for the campus tutoring service.",
    collections: ["Business"],
    tags: ["offer", "copy", "solo"],
    daysAgo: 15,
    lastOpenedDaysAgo: 15,
    openCount: 1,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/THUMBNAILCROP/",
    sourceType: "instagram_reel",
    creatorName: "editsbykira",
    title: "Thumbnail faces that read at 80px",
    userNote: "Crop tighter than feels polite. High contrast text, one verb.",
    collections: ["Editing Ideas", "Watch Later"],
    tags: ["thumbnail", "youtube", "reference"],
    daysAgo: 4,
    openCount: 0,
  },
  {
    sourceUrl: "https://www.instagram.com/reel/POMODORO/",
    sourceType: "instagram_reel",
    creatorName: "study.lighthouse",
    title: "A pomodoro setup that survives group chat",
    userNote: "Try this during midterms. Phone in another room is the actual feature.",
    collections: ["College"],
    tags: ["study", "productivity"],
    daysAgo: 5,
    lastOpenedDaysAgo: 5,
    openCount: 1,
  },
  {
    sourceUrl: "https://www.instagram.com/p/UNSORTED99/",
    sourceType: "instagram_post",
    creatorName: "random.tabs",
    title: "A post I saved in a hurry",
    userNote: "",
    collections: ["Inbox"],
    tags: [],
    daysAgo: 1,
    openCount: 0,
    needsReview: true,
  },
  {
    sourceUrl: "https://www.thekitchn.com/weeknight-dal",
    sourceType: "web_link",
    creatorName: "The Kitchn",
    title: "Weeknight dal that freezes well",
    userNote: "Not Instagram. Keep web recipes in the same library.",
    collections: ["Recipes"],
    tags: ["dal", "meal-prep"],
    daysAgo: 19,
    lastOpenedDaysAgo: 3,
    openCount: 2,
  },
];
